onherroepelijk:
- synoniem: kracht van gewijsde
  weight: 0.95
- synoniem: rechtskracht
  weight: 0.9
- synoniem: in kracht van gewijsde
  weight: 0.95
- synoniem: definitieve uitspraak
  weight: 0.85
- synoniem: finale uitspraak
  weight: 0.8
- synoniem: onherroepelijke veroordeling
  weight: 0.75
- synoniem: definitief
  weight: 0.9
- synoniem: bindend
  weight: 0.85
- synoniem: onbetwistbaar
  weight: 0.8
- synoniem: onaantastbaar
  weight: 0.8
- synoniem: onveranderlijk
  weight: 0.8
- synoniem: onwrikbaar
  weight: 0.75
voorlopige_hechtenis:
- synoniem: voorarrest
  weight: 0.95
- synoniem: bewaring
  weight: 0.9
- synoniem: inverzekeringstelling
  weight: 0.85
- synoniem: preventieve detentie
  weight: 0.8
- synoniem: voorlopige vrijheidsbeneming
  weight: 0.85
- synoniem: gevangenhouding
  weight: 0.7
verdachte:
- synoniem: beklaagde
  weight: 0.9
- synoniem: beschuldigde
  weight: 0.9
- synoniem: aangeklaagde
  weight: 0.85
- synoniem: gedetineerde
  weight: 0.6
- synoniem: verdacht persoon
  weight: 0.8
dagvaarding:
- synoniem: oproeping
  weight: 0.85
- synoniem: gerechtelijke oproeping
  weight: 0.9
- synoniem: procesinleiding
  weight: 0.75
- synoniem: dagvaardingsexploot
  weight: 0.95
aanhouding:
- synoniem: arrestatie
  weight: 0.95
- synoniem: vrijheidsberoving
  weight: 0.8
- synoniem: staandehouding
  weight: 0.85
schorsing:
- opschorting
- tijdelijke opschorting
- voorwaardelijke opschorting
schuldig:
- schuldigverklaring
- veroordeling
- strafrechtelijke aansprakelijkheid
- strafrechtelijke verantwoordelijkheid
strafbaar_feit:
- delict
- misdrijf
- overtreding
- strafbaar handelen
- criminele gedraging
hoger_beroep:
- synoniem: appel
  weight: 0.95
- synoniem: appelprocedure
  weight: 0.9
- synoniem: beroepsinstantie
  weight: 0.7
cassatie:
- synoniem: hogere voorziening
  weight: 0.85
- synoniem: cassatieberoep
  weight: 0.95
- synoniem: vernietiging
  weight: 0.6
- synoniem: cassatieprocedure
  weight: 0.9
vonnis:
- synoniem: uitspraak
  weight: 0.9
- synoniem: rechterlijke beslissing
  weight: 0.85
- synoniem: gerechtelijke uitspraak
  weight: 0.9
- synoniem: arrest
  weight: 0.85
getuige:
- getuigenis
- getuigenbewijs
- testimonium
- verklaring onder ede
- synoniem: getuigenis afleggende persoon
  weight: 0.95
- synoniem: verklarende
  weight: 0.9
- synoniem: bewijsleverende persoon
  weight: 0.9
- synoniem: ooggetuige
  weight: 0.85
- synoniem: verschijnende
  weight: 0.85
- synoniem: informant
  weight: 0.8
bewijs:
- bewijsvoering
- bewijsmiddel
- bewijsmateriaal
- bewijsstuk
procesdossier:
- processtukken
- gerechtelijk dossier
- rechtbankdossier
beschikking:
- synoniem: besluit
  weight: 0.9
- synoniem: bestuursrechtelijk besluit
  weight: 0.95
- synoniem: overheidsbesluit
  weight: 0.85
- synoniem: ambtelijke beschikking
  weight: 0.9
bezwaar:
- synoniem: bezwaarschrift
  weight: 0.9
- synoniem: bezwaarprocedure
  weight: 0.95
- synoniem: administratief beroep
  weight: 0.8
- synoniem: primair rechtsmiddel
  weight: 0.75
beroep:
- synoniem: beroepsprocedure
  weight: 0.95
- synoniem: bestuursrechtelijke procedure
  weight: 0.9
- synoniem: rechterlijk beroep
  weight: 0.85
belanghebbende:
- synoniem: derde-belanghebbende
  weight: 0.85
- synoniem: rechtstreeks belanghebbende
  weight: 0.9
- synoniem: procespartij
  weight: 0.75
- synoniem: benadeelde
  weight: 0.7
horen:
- hoorzitting
- gehoor
- recht op horen
- auditu et altera parte
overeenkomst:
- synoniem: contract
  weight: 0.95
- synoniem: verbintenis
  weight: 0.85
- synoniem: contractuele afspraak
  weight: 0.9
- synoniem: zakelijke overeenkomst
  weight: 0.8
wanprestatie:
- synoniem: contractbreuk
  weight: 0.9
- synoniem: tekortkoming
  weight: 0.95
- synoniem: niet-nakoming
  weight: 0.9
- synoniem: schending overeenkomst
  weight: 0.85
schadevergoeding:
- smartengeld
- compensatie
- materiële schade
- immateriële schade
- vergoeding
onrechtmatige_daad:
- tort
- onrechtmatig handelen
- civielrechtelijke aansprakelijkheid
eigendom:
- bezit
- eigendomsrecht
- zakelijk recht
- vermogensrecht
wilsbekwaamheid:
- handelingsbekwaamheid
- rechtsbevoegdheid
- meerderjarigheid
rechter:
- magistraat
- rechterlijke macht
- zittingsrechter
- kantonrechter
- voorzieningenrechter
advocaat:
- raadsman
- juridisch vertegenwoordiger
- rechtsbijstand
- procureur (België)
openbaar_ministerie:
- OM
- officier van justitie
- parket
- vervolgingsinstantie
rechtbank:
- gerecht
- gerechtshof
- justitieel orgaan
gevangenisstraf:
- vrijheidsstraf
- onvoorwaardelijke gevangenisstraf
- detentie
- opsluiting
taakstraf:
- werkstraf
- dienstverlening
- alternatieve straf
voorwaardelijke_straf:
- voorwaardelijk opleggen
- straf met proeftijd
- voorwaarden gestelde straf
geldboete:
- boete
- geldelijke straf
- pecuniaire sanctie
jeugddetentie:
- PIJ-maatregel
- jeugdgevangenis
- jeugdinrichting
- juveniele detentie
kinderrechter:
- jeugdrechter
- kinderrechterlijke macht
rechtspersoon:
- juridische persoon
- rechtspersoonlijkheid
- vennootschap
- stichting (in context)
verjaring:
- verjaringstermijn
- bevrijdende verjaring
- verjaringsgrond
redelijkheid:
- redelijkheid en billijkheid
- goede trouw
- deugdelijkheid
opzet:
- intentie
- moedwilligheid
- opzettelijk handelen
- dolus
schuld:
- culpa
- nalatigheid
- verwijtbaarheid
rechtsmiddel:
- remedie
- beroepsmogelijkheid
- rechtsherstel
uitvoerbaar_bij_voorraad:
- provisioneel
- voorlopige uitvoerbaarheid
- onmiddellijke tenuitvoerlegging
_clusters:
  rechtsmiddelen:
  - rechtsmiddel
  - hoger_beroep
  - cassatie
  - verzet
  - herziening
  straffen:
  - gevangenisstraf
  - taakstraf
  - geldboete
  - voorwaardelijke_straf
  - jeugddetentie
  procedureel_strafrecht:
  - voorlopige_hechtenis
  - aanhouding
  - schorsing
  - dagvaarding
  - wraking
  partijen_strafrecht:
  - verdachte
  - advocaat
  - rechter
  - openbaar_ministerie
  bestuursrecht_procedures:
  - beschikking
  - bezwaar
  - beroep
  - horen
  - belanghebbende
  burgerlijk_procedures:
  - overeenkomst
  - wanprestatie
  - schadevergoeding
  - vonnis
  - onrechtmatige_daad
  juridische_bewijsvoering:
  - bewijs
  - getuige
  - procesdossier
  strafrechtelijke_verantwoordelijkheid:
  - schuldig
  - strafbaar_feit
  - opzet
  - schuld
  - recidive
  - medeplegen
recidive:
- herhaling
- wederom strafbaar feit
- terugval
medeplegen:
- medeplichtigheid
- deelneming
- medeplichtige
mandaat:
- volmacht
- delegatie
- bevoegdheidsoverdracht
deugdelijke_motivering:
- motiveringsplicht
- zorgvuldigheidsbeginsel
- behoorlijk bestuur
comparitie:
- comparitie van partijen
- voorlopige zitting
- verschijning
wraking:
- wrakingsverzoek
- rechter-wraking
- onpartijdigheid
richtlijn:
- EU-richtlijn
- Europese richtlijn
- implementatieverplichting
verordening:
- EU-verordening
- Europese verordening
- rechtstreekse werking
